---
title: "Ingresso no Serviço Público Federal por Meio de Cota Racial"
output: html_document
resource_files:
  - '.'
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{=html}

<style type="text/css"> 
h1.title {
    font-size: 30px;
}

body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
}

</style>
```

```{r}
library(readr)
library(dplyr)
library(reactable)
library(htmltools)

cotas <- read_csv("data/cotas.csv", locale = locale(encoding = "ISO-8859-1"))

# adicionar mais uma coluna na condicao de cota receberá o valor 1 e 0 caso contrário

cotas <- cotas %>% mutate(cota = ifelse(tipo_cota == "Cota Racial", 1, 0))

# sumarizar os dados para saber a quantidade DISTINTOS de gr_mat por NO_ORGAO E NO_CARGO

subdata <- cotas %>% 
  group_by(NO_ORGAO, NO_CARGO_ORIGEM) %>% 
  summarise(count_gr_mat = n_distinct(gr_mat), 
            cotas = sum(cota),
            Percentual.cotas = round(cotas/count_gr_mat,2),
            qte_20 = count_gr_mat * 0.2,
            diferenca = qte_20 - cotas)

data <- cotas %>% 
  group_by(NO_ORGAO) %>% 
  summarise(count_gr_mat = n_distinct(gr_mat), 
            cotas = sum(cota),
            Percentual.cotas = round(cotas/count_gr_mat,2),
            qte_20 = count_gr_mat * 0.2,
            diferenca = qte_20 - cotas)

# data <- clipr::read_clip_tbl()
# 
# data <- data %>%
#   mutate(
#     Percentual.cota = readr::parse_number(Percentual.cota, locale = locale(decimal_mark = ","))
#   )

# Salvar data em um pasta local

# write_csv(data, "data/data.csv")

# subdata <- clipr::read_clip_tbl()
# 
# subdata <- subdata %>%
#   mutate(
#     Percentual.cota = readr::parse_number(Percentual.cota, locale = locale(decimal_mark = ","))
#   )

# Salvar data em um pasta local


# write_csv(subdata, "data/subdata.csv")

data <- read_csv("data/data.csv") 

subdata <- read_csv("data/subdata.csv")

data <- data  |> 
 select(NO_ORGAO, NO_CARGO_ORIGEM, count_gr_mat, cotas, Percentual.cotas)  

subdata <- subdata |> 
  select(NO_ORGAO, NO_CARGO_ORIGEM, count_gr_mat, cotas, Percentual.cotas)

tbl <- reactable(
  data,
  
  pagination = TRUE,
  searchable =  TRUE,
  defaultSorted = "Percentual.cotas",
  defaultColDef = colDef(headerClass = "header", align = "left"),
  columns = list(
    NO_ORGAO = colDef(
      name = "Órgão",
      width = 150
    ),
    NO_CARGO_ORIGEM = colDef(name="", maxWidth=130, align="left"),
    count_gr_mat = colDef(
      name = "Total de Servidores",
      defaultSortOrder = "desc",
      cell = function(value) {
        width <- paste0(value * 100 / max(data$followers), "%")
        value <- format(value, big.mark = ",")
        value <- format(value, width = 9, justify = "right")
        bar <- div(
          class = "bar-chart",
          style = list(marginRight = "0.375rem"),
          div(class = "bar", style = list(width = width, backgroundColor = "#3fc1c9"))
        )
        div(class = "bar-cell", span(class = "number", value), bar)
      }
    ),
    Percentual.cotas = colDef(
      name = "% Cota Racial",
      defaultSortOrder = "desc",
      cell = JS('function(cellInfo) {
        // Format as percentage
        const pct = (cellInfo.value * 100).toFixed(1) + "%"
        // Pad single-digit numbers
        let value = pct.padStart(5)
        // Show % on first row only
        if (cellInfo.viewIndex > 0) {
          value = value.replace("%", " ")
        }
        // Render bar chart
        return `
          <div class="bar-cell">
            <span class="number">${value}</span>
            <div class="bar-chart" style="background-color: #e1e1e1">
              <div class="bar" style="width: ${pct}; background-color: #fc5185"></div>
            </div>
          </div>
        `
      }'),
      html = TRUE
    )
  ),
  compact = TRUE,
  class = "followers-tbl",
  
    #Sub-Table
  details = function(index){
    new = subdata[subdata$NO_ORGAO == data$NO_ORGAO[index],]
    reactable(data=new,
              defaultSorted = "Percentual.cotas",
              defaultColDef = colDef(headerClass = "header", align = "left"),
              columns = list(
                NO_ORGAO = colDef( show = FALSE,
                  name = "Órgão",
                  width = 150
                ),
                NO_CARGO_ORIGEM = colDef(name="Cargo", maxWidth=130, align="left"),
                count_gr_mat = colDef(
                  name = "Total de Servidores",
                  defaultSortOrder = "desc",
                  cell = function(value) {
                    width <- paste0(value * 100 / max(data$followers), "%")
                    value <- format(value, big.mark = ",")
                    value <- format(value, width = 9, justify = "right")
                    bar <- div(
                      class = "bar-chart",
                      style = list(marginRight = "0.375rem"),
                      div(class = "bar", style = list(width = width, backgroundColor = "#3fc1c9"))
                    )
                    div(class = "bar-cell", span(class = "number", value), bar)
                  }
                ),
                Percentual.cotas = colDef(
                  name = "% Cota Racial",
                  defaultSortOrder = "desc",
                  cell = JS('function(cellInfo) {
        // Format as percentage
        const pct = (cellInfo.value * 100).toFixed(1) + "%"
        // Pad single-digit numbers
        let value = pct.padStart(5)
        // Show % on first row only
        if (cellInfo.viewIndex > 0) {
          value = value.replace("%", " ")
        }
        // Render bar chart
        return `
          <div class="bar-cell">
            <span class="number">${value}</span>
            <div class="bar-chart" style="background-color: #e1e1e1">
              <div class="bar" style="width: ${pct}; background-color: #fc5185"></div>
            </div>
          </div>
        `
      }'),
      html = TRUE
                )
              ),
      compact = TRUE,
      class = "followers-tbl"
      
    )
  }, 
  elementId = "cars-download-table"
  
)

htmltools::browsable(
  tagList(
    div(class = "twitter-followers",
        div(class = "followers-header",
            h1(class = "followers-title"), #"Inclusão Racial no Serviço Público Federal: Análise das Cotas Raciais nos Concursos"),
            "Percentual de Ingresso de Servidores Públicos Federais por Meio de Cotas Raciais a partir de novembro de 2023 a junho de 2024"
        )
    ),
    tbl,
    tags$button(
      tagList(fontawesome::fa("download"), "Baixar Dados"),
      onclick = "Reactable.downloadDataCSV('cars-download-table', 'cotas.csv')"

    ),
    
    
  )
)
```


```{r}
htmltools::tags$link(href = "https://fonts.googleapis.com/css?family=Karla:400,700|Fira+Mono&display=fallback", rel = "stylesheet")
```


```{css}

.main-container {
    max-width: 1000px;
    margin-left: auto;
    margin-right: auto;
}

.twitter-followers {
  margin: 0 auto;
  width: 850px;
  font-family: Karla, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.followers-header {
  margin: 1.125rem 0;
  font-size: 1rem;
}

.followers-title {
  font-size: 1.25rem;
  font-weight: 600;
}

.followers-tbl {
  font-size: 0.875rem;
  line-height: 1.125rem;
}

.followers-tbl a {
  color: inherit;
  text-decoration: none;
}

.followers-tbl a:hover,
.followers-tbl a:focus {
  text-decoration: underline;
  text-decoration-thickness: max(1px, 0.0625rem);
}

.header {
  border-bottom: 2px solid #555;
  font-size: 0.8125rem;
  font-weight: 400;
  text-transform: uppercase;
}

.header:hover {
  background-color: #eee;
}

.bar-cell {
  display: flex;
  align-items: center;
}

.number {
  font-family: "Fira Mono", Consolas, Monaco, monospace;
  font-size: 0.84375rem;
  white-space: pre;
}

.bar-chart {
  flex-grow: 1;
  margin-left: 0.375rem;
  height: 0.875rem;
}

.bar {
  height: 100%;
}
```

